<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * One row per app install.
     *
     * The mobile app has no accounts, but a submission still has to be
     * attributable: so the person who added a book can later propose an edit
     * to it, and so a single install that uploads rubbish can be blocked
     * without punishing everyone behind the same address.
     */
    public function up(): void
    {
        Schema::create('devices', function (Blueprint $table) {
            $table->id();
            // Generated by the app on first launch and kept in the keychain.
            $table->uuid('uuid')->unique();
            $table->string('platform', 32)->nullable();
            $table->string('app_version', 32)->nullable();
            $table->timestamp('last_seen_at')->nullable();
            // Set by a human to stop an abusive install submitting anything.
            $table->timestamp('blocked_at')->nullable()->index();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('devices');
    }
};
